### ISSUE TITLE
error when running the program

### ISSUE THREAD

**Issue by USAMAWIZARD** [jpy-consortium/jpy#100]
ubuntu20.04
python3.8
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
package org.jpy;

public class JPyExample {
    public static void main(String[] args) {
        long pyModule;
        // Start the Python interpreter
        PyLib.startPython();
        pyModule = PyLib.importModule("script");

        // Call the Python function
        PyModule sys = PyModule.importModule("script");

        PyObject pyFunc = sys.call("printfff", "1");
        String result = pyFunc.toString();
        System.out.println("Result: " + result);

        // Stop the Python interpreter
        PyLib.stopPython();
    }
}



java  -Djpy.jpyLib=/home/usama/Pictures/jpy/build/lib.linux-x86_64-3.8/jpy.cpython-38-x86_64-linux-gnu.so -Djpy.jdlLib=/home/usama/Pictures/jpy/build/lib.linux-x86_64-3.8/jdl.cpython-38-x86_64-linux-gnu.so -cp jpy.jar:. org.jpy.JPyExample
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/usama/Pictures/jpy/build/lib.linux-x86_64-3.8/jpy.cpython-38-x86_64-linux-gnu.so: /home/usama/Pictures/jpy/build/lib.linux-x86_64-3.8/jpy.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyModule_Type
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.jpy.PyLib.loadLib(PyLib.java:508)
        at org.jpy.PyLib.<clinit>(PyLib.java:567)
        at org.jpy.JPyExample.main(JPyExample.java:8

```

**Comment by devinrsmith** [comment]
Hi - you may need libpython static libraries installed.

Can you try `apt-get update && apt-get install libpython3.8` and report back if that fixes the problem?

**Comment by USAMAWIZARD** [comment]
Thanks I statically linked -Djpy.pythonLib and that fixed the issue
