### ISSUE TITLE
java.lang.IllegalArgumentException: pointer == 0

### ISSUE THREAD

**Issue by devinrsmith** [jpy-consortium/jpy#83]
```
java.lang.IllegalArgumentException: pointer == 0
        at org.jpy.PyObjectState.<init>(PyObjectState.java:20)
        at org.jpy.PyObject.<init>(PyObject.java:72)
        at org.jpy.PyObject.<init>(PyObject.java:67)
        at org.jpy.PyObject.executeCode(PyObject.java:138)
```

```python
import io
import jpy

_j_out = jpy.get_type('java.lang.System').out

class BadFoo(io.TextIOBase):
    def __init__(self):
        raise Exception("I hate fun")

    def close(self):
        _j_out.println("time to close")

BadFoo()
```

With a java initiated python session, calling this as input to `PyObject.executeCode("BadFoo()", PyInputMode.SCRIPT);` causes the exception shown above.

**Comment by devinrsmith** [comment]
@jmao-denver @niloc132 have done a lot of the triage work:

> we dont know conclusively what the exact path is to failure, but the JPy_ON_JAVA_EXCEPTION_GOTO that happens in jmethod's InvokeMethod might be seeing the java exception set when it returns, and translating that back to python and TextIOBase's close just eats any exception that happens during finalize

**Comment by devinrsmith** [comment]
Reproduction: https://github.com/devinrsmith/deephaven-core/tree/println-bad-foo
